name: 🚨 Branch Watchdog

on:
  push:
    branches: [main, dev]
  schedule:
    - cron: '0 * * * *' # stündlich

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Hole Branch-Liste
        run: |
          BRANCH_COUNT=$(git ls-remote --heads origin | wc -l)
          echo "Aktive Branches: $BRANCH_COUNT"
          if [ "$BRANCH_COUNT" -gt 2 ]; then
            echo "::warning ::Mehr als 2 Branches erkannt – Zusammenführung empfohlen!"
            exit 0
          fi
