# .github/workflows/validate.yml

name: 🔍 Modultool-Codeprüfung & Barrierecheck

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  validate:
    name: 🔧 Struktur-, Syntax- und Barrierefreiheitstests
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Repository auschecken
      uses: actions/checkout@v4

    - name: 🧰 Abhängigkeiten installieren
      run: |
        sudo apt-get update
        sudo apt-get install -y jq shellcheck curl npm
        npm install -g jsonlint htmlhint axe-core

    # 🔍 JSON-Prüfung aller Dateien
    - name: ✅ JSON-Struktur validieren
      run: |
        find . -name "*.json" -not -path "./node_modules/*" -exec jsonlint -q {} \;

    # 🧪 HTMLHint: Barriere- und Strukturprüfung von .html-Dateien
    - name: ✅ HTML-Struktur prüfen
      run: |
        find . -name "*.html" -not -path "./node_modules/*" -exec htmlhint {} \;

    # 🧼 Shell-Skripte auf Fehler prüfen
    - name: ✅ Shell-Skripte prüfen
      run: |
        find . -name "*.sh" -exec shellcheck {} +

    # ♿ Accessibility Check mit axe-core (Headless Chrome)
    - name: ♿ Accessibility-Test mit axe-core
      run: |
        npx axe https://example.com --quiet || echo "⚠️ Hinweis: axe-core benötigt ein testbares Deployment mit URL."
      continue-on-error: true

    # 📂 Projektstruktur anzeigen (optional logbar)
    - name: 📂 Projektstruktur auflisten
      run: |
        find . -type f | sort
